// Interface automatically generated by schemas-to-ts

import { ArtTag } from '../../../art-tag/content-types/art-tag/art-tag';
import { ArtCategory } from '../../../art-category/content-types/art-category/art-category';
import { ArtTag_Plain } from '../../../art-tag/content-types/art-tag/art-tag';
import { ArtCategory_Plain } from '../../../art-category/content-types/art-category/art-category';
import { AdminPanelRelationPropertyModification } from '../../../../common/sharedSchemas/AdminPanelRelationPropertyModification';

export interface ArtTagCategory {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    name: string;
    art_tags: { data: ArtTag[] };
    display_name: string;
    art_categories?: { data: ArtCategory[] };
    locale: string;
    localizations?: { data: ArtTagCategory[] };
  };
}
export interface ArtTagCategory_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  art_tags: ArtTag_Plain[];
  display_name: string;
  art_categories?: ArtCategory_Plain[];
  locale: string;
  localizations?: ArtTagCategory_Plain[];
}

export interface ArtTagCategory_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  art_tags: number[];
  display_name: string;
  art_categories?: number[];
  locale: string;
  localizations?: ArtTagCategory[];
}

export interface ArtTagCategory_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  art_tags: AdminPanelRelationPropertyModification<ArtTag_Plain>;
  display_name: string;
  art_categories?: AdminPanelRelationPropertyModification<ArtCategory_Plain>;
  locale: string;
  localizations?: ArtTagCategory[];
}
