services:

  postgres:
    hostname: postgres
    container_name: postgres
    image: postgres:17.5
    restart: always
    environment:
      - POSTGRES_DB=portfolio-joel
      - PGDATA=/data/postgres
    env_file:
      - stack.env
    ports:
      - 5432:5432
    volumes:
      - db:/data/postgres

  strapi:
    container_name: strapi
    image: harbor.frozox.fr/portfolio-joel/strapi:latest
    restart: always
    build:
      dockerfile: ./deploy/docker/Dockerfile
      target: strapi
      platforms:
        - linux/amd64
        - linux/arm64
    env_file:
      - stack.env
    ports:
      - 8137:1337
    volumes:
      - uploads:/prod/strapi/public/uploads

  nextjs:
    container_name: nextjs
    image: harbor.frozox.fr/portfolio-joel/nextjs:latest
    restart: always
    build:
      dockerfile: ./deploy/docker/Dockerfile
      target: nextjs
      platforms:
        - linux/amd64
        - linux/arm64
    env_file:
      - stack.env
    ports:
      - 8300:3000

volumes:
  db:
  uploads: