// Interface automatically generated by schemas-to-ts

export interface New {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    content?: any;
    locale: string;
    localizations?: { data: New[] };
  };
}
export interface New_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  content?: any;
  locale: string;
  localizations?: New_Plain[];
}

export interface New_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  content?: any;
  locale: string;
  localizations?: New[];
}

export interface New_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  content?: any;
  locale: string;
  localizations?: New[];
}
