// Interface automatically generated by schemas-to-ts

import { Art } from '../../../art/content-types/art/art';
import { Art_Plain } from '../../../art/content-types/art/art';
import { AdminPanelRelationPropertyModification } from '../../../../common/sharedSchemas/AdminPanelRelationPropertyModification';

export interface ArtTag {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    tag: string;
    arts?: { data: Art[] };
    locale: string;
    localizations?: { data: ArtTag[] };
  };
}
export interface ArtTag_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  tag: string;
  arts?: Art_Plain[];
  locale: string;
  localizations?: ArtTag[];
}

export interface ArtTag_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  tag: string;
  arts?: number[];
  locale: string;
  localizations?: ArtTag[];
}

export interface ArtTag_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  tag: string;
  arts?: AdminPanelRelationPropertyModification<Art_Plain>;
  locale: string;
  localizations?: ArtTag[];
}
