// Interface automatically generated by schemas-to-ts

import { Art } from '../../../art/content-types/art/art';
import { ArtTagCategory } from '../../../art-tag-category/content-types/art-tag-category/art-tag-category';
import { Art_Plain } from '../../../art/content-types/art/art';
import { ArtTagCategory_Plain } from '../../../art-tag-category/content-types/art-tag-category/art-tag-category';
import { AdminPanelRelationPropertyModification } from '../../../../common/sharedSchemas/AdminPanelRelationPropertyModification';

export interface ArtTag {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    tag: string;
    arts?: { data: Art[] };
    art_tag_category?: { data: ArtTagCategory };
    locale: string;
    localizations?: { data: ArtTag[] };
  };
}
export interface ArtTag_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  tag: string;
  arts?: Art_Plain[];
  art_tag_category?: ArtTagCategory_Plain;
  locale: string;
  localizations?: ArtTag_Plain[];
}

export interface ArtTag_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  tag: string;
  arts?: number[];
  art_tag_category?: number;
  locale: string;
  localizations?: ArtTag[];
}

export interface ArtTag_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  tag: string;
  arts?: AdminPanelRelationPropertyModification<Art_Plain>;
  art_tag_category?: AdminPanelRelationPropertyModification<ArtTagCategory_Plain>;
  locale: string;
  localizations?: ArtTag[];
}
