// Interface automatically generated by schemas-to-ts

import { Media } from '../../../common/sharedSchemas/Media';
import { Media_Plain } from '../../../common/sharedSchemas/Media';

export interface MediaComponent {
  media: { data: Media };
}
export interface MediaComponent_Plain {
  media: Media_Plain;
}

export interface MediaComponent_NoRelations {
  media: number;
}

