// Interface automatically generated by schemas-to-ts

import { Media } from '../../../common/sharedSchemas/Media';
import { Media_Plain } from '../../../common/sharedSchemas/Media';

export enum MediaPosition {
  Left = 'left',
  Right = 'right',}
export enum MediaMobilePosition {
  Top = 'top',
  Bottom = 'bottom',}

export interface TextMediaComponent {
  content: string;
  media: { data: Media };
  media_position: MediaPosition;
  media_mobile_position: MediaMobilePosition;
}
export interface TextMediaComponent_Plain {
  content: string;
  media: Media_Plain;
  media_position: MediaPosition;
  media_mobile_position: MediaMobilePosition;
}

export interface TextMediaComponent_NoRelations {
  content: string;
  media: number;
  media_position: MediaPosition;
  media_mobile_position: MediaMobilePosition;
}

