// Interface automatically generated by schemas-to-ts

export interface TextComponent {
  content: any;
}
export interface TextComponent_Plain {
  content: any;
}

export interface TextComponent_NoRelations {
  content: any;
}

