// Interface automatically generated by schemas-to-ts

import { Art } from '../../../art/content-types/art/art';
import { Media } from '../../../../common/sharedSchemas/Media';
import { ArtTagCategory } from '../../../art-tag-category/content-types/art-tag-category/art-tag-category';
import { Art_Plain } from '../../../art/content-types/art/art';
import { Media_Plain } from '../../../../common/sharedSchemas/Media';
import { ArtTagCategory_Plain } from '../../../art-tag-category/content-types/art-tag-category/art-tag-category';
import { AdminPanelRelationPropertyModification } from '../../../../common/sharedSchemas/AdminPanelRelationPropertyModification';

export interface ArtCategory {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    name: string;
    arts: { data: Art[] };
    image: { data: Media };
    slug: string;
    art_tag_categories?: { data: ArtTagCategory[] };
    locale: string;
    localizations?: { data: ArtCategory[] };
  };
}
export interface ArtCategory_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  arts: Art_Plain[];
  image: Media_Plain;
  slug: string;
  art_tag_categories?: ArtTagCategory_Plain[];
  locale: string;
  localizations?: ArtCategory_Plain[];
}

export interface ArtCategory_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  arts: number[];
  image: number;
  slug: string;
  art_tag_categories?: number[];
  locale: string;
  localizations?: ArtCategory[];
}

export interface ArtCategory_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  arts: AdminPanelRelationPropertyModification<Art_Plain>;
  image: AdminPanelRelationPropertyModification<Media_Plain>;
  slug: string;
  art_tag_categories?: AdminPanelRelationPropertyModification<ArtTagCategory_Plain>;
  locale: string;
  localizations?: ArtCategory[];
}
