// Interface automatically generated by schemas-to-ts

import { Art } from '../../../art/content-types/art/art';
import { Media } from '../../../../common/sharedSchemas/Media';
import { Art_Plain } from '../../../art/content-types/art/art';
import { AdminPanelRelationPropertyModification } from '../../../../common/sharedSchemas/AdminPanelRelationPropertyModification';

export interface ArtCategory {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    name: string;
    arts: { data: Art[] };
    image: { data: Media };
    slug: string;
    locale: string;
    localizations?: { data: ArtCategory[] };
  };
}
export interface ArtCategory_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  arts: Art_Plain[];
  image: Media;
  slug: string;
  locale: string;
  localizations?: ArtCategory[];
}

export interface ArtCategory_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  arts: number[];
  image: number;
  slug: string;
  locale: string;
  localizations?: ArtCategory[];
}

export interface ArtCategory_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  arts: AdminPanelRelationPropertyModification<Art_Plain>;
  image: AdminPanelRelationPropertyModification<Media>;
  slug: string;
  locale: string;
  localizations?: ArtCategory[];
}
